version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
      
  web:
    image: niktere/ride_recording:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web 

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot -webroot-path=/var/www/html --email nikterekhoff4242@gmail.com --agree-tos --no-eff-email -d broniryu-itochka.ddns.net

volumes:
  static_value:
  media_value:
  database:
  www-html:
  etc-letsencrypt: