# Generated by Django 2.2.16 on 2022-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='contact',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
