# Generated by Django 2.2.16 on 2022-01-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='end_date',
            field=models.TimeField(),
        ),
    ]
