# Generated by Django 2.2.16 on 2022-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='high_duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='high_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='low_duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='low_time',
            field=models.TimeField(),
        ),
    ]
