# Generated by Django 2.2.16 on 2022-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20220513_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
