# Generated by Django 2.2.16 on 2022-01-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20220129_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
