# Generated by Django 2.2.16 on 2022-01-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20220129_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
