# Generated by Django 2.2.16 on 2022-05-13 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20220513_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='high_duration',
            field=models.IntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='services',
            name='high_time',
            field=models.IntegerField(default=24, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='services',
            name='low_duration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='services',
            name='low_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
