# Generated by Django 2.2.16 on 2022-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20220129_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='records',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
