# Generated by Django 2.2.16 on 2022-01-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20220129_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='start_time',
            field=models.DateField(),
        ),
    ]
