# Generated by Django 2.2.16 on 2022-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20220129_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
