# Generated by Django 2.2.16 on 2022-03-26 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0009_auto_20220130_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='car_or_ship',
        ),
        migrations.AddField(
            model_name='records',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='records',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Records_ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
