# Generated by Django 2.2.16 on 2022-04-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20220326_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
