# Generated by Django 2.2.16 on 2022-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_records_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='records_ship',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='records_ship',
            name='date_start',
            field=models.DateField(),
        ),
    ]
