# Generated by Django 2.2.16 on 2022-05-09 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Нужно записать номер телефона в формате 89001112233.', regex='^8\\d{10}$')]),
        ),
    ]
